export const contractData = [
    {
      contractId: 101,
      clientName: "Arya Stark",
      hallName: "Winterfell Banquet Hall",
      hallLocation: "North Street, Winterfell, NY",
      eventType: "Wedding",
      date: "2025-05-12",
      amountEarned: 2500,
      status: "Completed",
    },
    {
      contractId: 102,
      clientName: "Tyrion Lannister",
      hallName: "Casterly Rock Venue",
      hallLocation: "Gold Lane, Casterly Rock, CA",
      eventType: "Corporate",
      date: "2025-05-20",
      amountEarned: 1800,
      status: "Upcoming",
    },
    {
      contractId: 103,
      clientName: "Daenerys Targaryen",
      hallName: "Dragonstone Palace",
      hallLocation: "Bay View, Dragonstone, FL",
      eventType: "Wedding",
      date: "2025-06-05",
      amountEarned: 3000,
      status: "Upcoming",
    },
    {
      contractId: 104,
      clientName: "Sansa Stark",
      hallName: "Red Keep Events",
      hallLocation: "Main Road, King's Landing, TX",
      eventType: "Engagement",
      date: "2025-05-25",
      amountEarned: 1500,
      status: "Completed",
    },
    {
      contractId: 105,
      clientName: "Bran Stark",
      hallName: "Three-Eyed Raven Garden",
      hallLocation: "Mystic Hill, North Dakota",
      eventType: "Birthday",
      date: "2025-07-01",
      amountEarned: 1000,
      status: "Upcoming",
    },
    {
      contractId: 106,
      clientName: "Cersei Lannister",
      hallName: "Lannister Court Hall",
      hallLocation: "Lion's Way, Casterly Rock, CA",
      eventType: "Anniversary",
      date: "2025-04-28",
      amountEarned: 2200,
      status: "Completed",
    },
    {
      contractId: 107,
      clientName: "Samwell Tarly",
      hallName: "Oldtown Grand Hall",
      hallLocation: "Library Lane, Oldtown, MA",
      eventType: "Baby Shower",
      date: "2025-06-10",
      amountEarned: 1200,
      status: "Upcoming",
    },
    {
      contractId: 108,
      clientName: "Brienne of Tarth",
      hallName: "Tarth Royal Venue",
      hallLocation: "Sapphire Isle, Tarth, NC",
      eventType: "Corporate",
      date: "2025-07-18",
      amountEarned: 1700,
      status: "Upcoming",
    },
    {
      contractId: 109,
      clientName: "Theon Greyjoy",
      hallName: "Pyke Castle Courtyard",
      hallLocation: "Iron Islands, Pyke, WA",
      eventType: "Wedding",
      date: "2025-08-03",
      amountEarned: 2600,
      status: "Upcoming",
    },
    {
      contractId: 110,
      clientName: "Gendry Waters",
      hallName: "Storm's End Venue",
      hallLocation: "Stormlands Blvd, MO",
      eventType: "Birthday",
      date: "2025-05-30",
      amountEarned: 1100,
      status: "Completed",
    },
    {
      contractId: 111,
      clientName: "Jorah Mormont",
      hallName: "Bear Island Retreat",
      hallLocation: "Northern Shore, Alaska",
      eventType: "Engagement",
      date: "2025-04-22",
      amountEarned: 1300,
      status: "Completed",
    },
    {
      contractId: 112,
      clientName: "Jon Snow",
      hallName: "Night’s Watch Hall",
      hallLocation: "The Wall, Castle Black, MT",
      eventType: "Corporate",
      date: "2025-06-22",
      amountEarned: 1950,
      status: "Upcoming",
    },
  ];
  